### ISSUE TITLE
nice_number bug

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/lingua-franca#116]
havent looked into it more, but i got this
```python
area = nice_number(area, speech=True)
```

```
Traceback (most recent call last):
  File "/home/user/MycroftProjects/mycroft-core/.venv/lib/python3.8/site-packages/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/home/user/mycroft_data/skills/skill-countries/__init__.py", line 180, in handle_country_area
    area = nice_number(area, speech=True)
  File "/home/user/MycroftProjects/mycroft-core/.venv/lib/python3.8/site-packages/lingua_franca/format.py", line 264, in nice_number
    return nice_number_en(number, speech, denominators)
  File "/home/user/MycroftProjects/mycroft-core/.venv/lib/python3.8/site-packages/lingua_franca/lang/format_en.py", line 37, in nice_number_en
    result = convert_to_mixed_fraction(number, denominators)
  File "/home/user/MycroftProjects/mycroft-core/.venv/lib/python3.8/site-packages/lingua_franca/lang/format_common.py", line 32, in convert_to_mixed_fraction
    int_number = int(number)
ValueError: invalid literal for int() with base 10: '92090.0'
```

**Comment by ChanceNCounter** [comment]
That's bizarre. `int(92090.0)` returns 92090. `int(str(92090.0))` returns ValueError.

I don't wanna suggest a kludge as a hotfix, and I haven't looked at the code yet, but it's obviously coming *from* a string. If that value starts as a float and gets cast to a string, that should stop happening; otherwise, `int_number = int(float(number))` should solve it. That could be on a conditional, `int_number = int(number) if isinstance(number, float) else int(float(number))`, but that doesn't save any operations, just changes them.

This deserves a proper analysis, but that's the quick fix.

**Comment by ChanceNCounter** [comment]
I spaced out the last time I looked at this, I guess.

`nice_number()` takes a float and returns a string. Was `'92090.0'` a string on its way in?

**Comment by JarbasAl** [comment]
just noticed this was using a string, but i think we should handle this use case. a simple try: except: block casting to float should work
